### ISSUE TITLE
Settings.openSetting is not defined

### ISSUE THREAD

**Issue by monolithed** [rmrs/react-native-settings#12]
I've already tried:

```ts
import Settings from 'react-native-settings';
import {Settings} from 'react-native-settings';
import * as Settings from 'react-native-settings';

await Settings.openSettings(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
```

![img-2017-11-26-21-00-59](https://user-images.githubusercontent.com/803674/33242923-15de268c-d2ed-11e7-9a94-2a919d6844f8.png)

PS: compiled from TypeScript:

```js
yield react_native_settings_1.default.openSettings(react_native_settings_1.default.ACTION_LOCATION_SOURCE_SETTINGS);
```

```
➜ uname -a
Darwin msk-wifi-20fap7-a_abashkin-a.mail.msk 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64

➜ node -v
v8.6.0

➜ npm -v
5.3.0

➜ npm run ts --version
5.3.0
```

[react-native-app-settings](https://github.com/KrazyLabs/react-native-app-settings) works fine

**Comment by erezrokah** [comment]
@monolithed Thank you for reporting this issue!
Can you provide some more information on your setup?

Android/iOS?
React Native version?
Did you run the `react-native link react-native-settings` command?
Can you verify your gradle file / Xcode Project has our library linked properly?
Maybe add a snippet of those files?

We don't have any experience with TypeScript so please explain what does it mean "compiled from TypeScript".
The best way might be to provide a git repo we can clone with a sample app that reproduces the issue, if possible.

Regards,
Erez

**Comment by monolithed** [comment]
> Android/iOS?

iOS

> React Native version?

0.49.5

> Did you run the react-native link react-native-settings command?

Yep

> Can you verify your gradle file / Xcode Project has our library linked properly?
Maybe add a snippet of those files?

I've already replaced react-native-settings with react-native-app-settings :(

> We don't have any experience with TypeScript so please explain what does it mean "compiled from TypeScript".

The source code of my project is written with TypeScript, but it doesn't matter....

**Comment by erezrokah** [comment]
Hello, again.

As stated in our readme, `openSetting` is an Android only functionality.

`react-native-settings` and `react-native-app-settings`, while having similar names, have different functionalities. 

`react-native-settings` allows you to access various **device** settings while `react-native-app-settings` allows you to access various **app** settings.

Example for a device setting: Cellular Data is enabled for the device. You'll reach that setting using Settings -> Cellular.

Example for an app setting: Cellular Data is enabled for your app. Let's say your app is Gmail. You'll reach that settings using Settings -> Gmail.

Accessing **app** settings is done in iOS using a URL scheme which is a public API:
https://developer.apple.com/documentation/uikit/uiapplication/settings_launch_url
https://github.com/KrazyLabs/react-native-app-settings/blob/7bce94b61d337b071b6cd58bd6ee583ac0843351/ios/RNOpenAppSettings.m

Accessing **device** settings can be done in iOS, but only using private APIs and can get an App rejected. 
See here for more information https://github.com/rmrs/react-native-settings/issues/1

**Comment by monolithed** [comment]
I got it, thanks!
