### ISSUE TITLE
'React/RCTDefines.h' file not found with RN 0.51

### ISSUE THREAD

**Issue by MoOx** [rmrs/react-native-settings#14]
I am trying to upgrade a project with RN 0.51 and I am facing an issue that comes from this module.
I will try to see if I can help but my native knowledge is clearly limited :)

**Comment by naviocean** [comment]
Try to remove node_modules folder and then run command below:
`npm install`

**Comment by erezrokah** [comment]
Closing due to lack of response

**Comment by MoOx** [comment]
Sorry I uninstalled this module and don't have time to investigate on this.
You will find plenty of lib having this issue when 0.51 cames out. See https://www.google.com/search?q=%27React/RCTDefines.h%27+file+not+found

**Comment by 0anw0** [comment]
I faced this error while working on ```react-native: 063.3``` ```react-native-settings:^1.0.0```: 
And this helped me fixing it: https://github.com/joltup/rn-fetch-blob/issues/461

**Comment by huy-lv** [comment]
same problem here
