### ISSUE TITLE
Help! touch id & passcode on ios

### ISSUE THREAD

**Issue by tackanoway35** [rmrs/react-native-settings#15]
How to open touch id & passcode setting on ios.
Thanks to help!

**Comment by erezrokah** [comment]
@tackanoway35 Thank you for opening this issue!
Please see my comment here about opening various settings in iOS https://github.com/rmrs/react-native-settings/issues/12#issuecomment-347190455

**Comment by erezrokah** [comment]
Closing due to no response, @tackanoway35  please open if you have any other questions
