### ISSUE TITLE
Listeners in ios

### ISSUE THREAD

**Issue by friendOfOurs** [rmrs/react-native-settings#17]
Hi guys,

I just wanted to check my assumptions that there is no way to have listeners listening to event GPS_PROVIDER_EVENT on ios?

Cheers

**Comment by erezrokah** [comment]
Hey,
Thank you for this issue.
Last time I checked I couldn't find a way to implement such a functionality (it might have changed).
See my comment here:
https://github.com/rmrs/react-native-settings/issues/13#issuecomment-351942729

On a way to achieve similar functionality using `AppState`.
