### ISSUE TITLE
TypeError: undefined is not an object( eveluating '_reactNativeSettings2.default.getSetting')

### ISSUE THREAD

**Issue by vohoangankhanh** [rmrs/react-native-settings#18]
I'm using create-react-native-app and expo and I'm facing this error, any solution? Thanks

**Comment by erezrokah** [comment]
Hello @vohoangankhanh and thank you for bringing this to our attention.
I don't think you can use external native modules (like this library) with expo.
You might need to detach/eject:
https://docs.expo.io/versions/latest/introduction/faq
https://docs.expo.io/versions/latest/guides/detach.html
https://forums.expo.io/t/clarification-on-3rd-party-components-compatible-with-expo/388/3
