### ISSUE TITLE
Update README docs please!

### ISSUE THREAD

**Issue by lunvjp** [rmrs/react-native-settings#19]
![image](https://user-images.githubusercontent.com/23715737/41457508-10f748d8-70ae-11e8-9842-ee9a4f55d07e.png)
![image](https://user-images.githubusercontent.com/23715737/41457538-3884f684-70ae-11e8-8bec-a20551335ea4.png)
Hope someone will update this for newbie.

**Comment by erezrokah** [comment]
Sorry for the very late reply, should be fixed in: https://github.com/rmrs/react-native-settings/commit/d6e4d01086c78469fdb356bfdfd91592bffe0299
