### ISSUE TITLE
Module RNSettings requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by binonxia** [rmrs/react-native-settings#20]
Module RNSettings requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup` In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by erezrokah** [comment]
Hey @binonxia, thanks for reporting this issue. We will be happy to accept a pr for this issue ;)

**Comment by dungnguyen10989** [comment]
add the hightligh code to RNSettings.m
<img width="1076" alt="screen shot 2018-10-08 at 1 46 01 am" src="https://user-images.githubusercontent.com/30271788/46585521-16248080-ca9c-11e8-8fdb-4aabd118450f.png">

**Comment by erezrokah** [comment]
Hey @dungnguyen10989 thanks for commenting. Do you mind opening a pr with the fix?

**Comment by dungnguyen10989** [comment]
@erezrokah please review and merge to master

**Comment by erezrokah** [comment]
Fixed by https://github.com/rmrs/react-native-settings/pull/21
