### ISSUE TITLE
Podspec with wrong tag

### ISSUE THREAD

**Issue by tiendn** [rmrs/react-native-settings#26]
https://github.com/rmrs/react-native-settings/blob/master/ios/RNSettings.podspec#L14
`s.source      = { :git => "https://github.com/rmrs/react-native-settings.git", :tag => "master" }`

There are two way to define source pod
* Use tag: change **master** to the lastest tag: **v0.0.1-alpha7**
* Use branch: replace **tag** -> **branch**

**Comment by erezrokah** [comment]
Hey @tiendn, thanks for the issue.
Do you want the open a pr for it?
I think it would make sense to replace **tag** with **branch**

**Comment by tiendn** [comment]
Yep, thanks for your response.
I think we should use **tag** for dynamic releases, like this 
```
require 'json'
version = JSON.parse(File.read('package.json'))["version"]

Pod::Spec.new do |s|
  s.version         = version
  s.source          = { :git => "https://github.com/rmrs/react-native-settings.git", :tag => "v" + s.version.to_s }
  ...
end

```

**Comment by erezrokah** [comment]
Looks much better. Can you open a pr for it?

**Comment by tiendn** [comment]
Okay.

**Comment by tiendn** [comment]
Sorry, but your version still **beta**.
And **cocoa pods** don't accept **beta** version. 
We need to fix version here.
