### ISSUE TITLE
cannot read property 'getSetting' of undefined

### ISSUE THREAD

**Issue by apurvaOyo** [rmrs/react-native-settings#29]

**Comment by erezrokah** [comment]
I'm having a hard time understating this issue due to lacking information.
I've added an issue template:
https://github.com/rmrs/react-native-settings/blob/master/.github/ISSUE_TEMPLATE/bug-issue-report.md

Can you please follow the instructions there?

**Comment by erezrokah** [comment]
Closing due to lack of response

**Comment by sabirbasha** [comment]
still the issue is there. your sample code directly will give this error.

**Comment by erezrokah** [comment]
Hi @sabirbasha, can you please open a new issue based on the issue template and add a reproduction scenario?
