### ISSUE TITLE
Does it support openning Captions settings on android?

### ISSUE THREAD

**Issue by shababcreative** [rmrs/react-native-settings#37]
Hi,
I'm looking for a way to open caption settings on android (Settings>Accessibility>Captions) from the app and I saw this package, does it support it?
The reason is that react-native-video subtitles depends on caption settings, and I want to add a shortcut for users to go directly to caption settings so that they can change the style.

**Comment by erezrokah** [comment]
Hey @shababcreative I think we'll need to add it. Shouldn't be too difficult though if you want to submit a PR - just need to find the right one here: https://developer.android.com/reference/android/provider/Settings

I think I'll be available to do it only next week.

**Comment by shababcreative** [comment]
@erezrokah I'm not good with native code XD
take your time doing it I think adding it will help many people

Thanks :)

**Comment by erezrokah** [comment]
Do you mind sharing a screenshot of the setting so I can make sure I add the correct one?

**Comment by shababcreative** [comment]
@erezrokah Settings>Accessibility>Captions (android 9 and the same in 5years old phone) 
![Screenshot_1575103449](https://user-images.githubusercontent.com/58214819/69898190-cae7c400-1366-11ea-92ea-bb6e4845362e.png)

**Comment by erezrokah** [comment]
Released in version `0.2.0`.
See example: https://github.com/rmrs/react-native-settings/blob/977cb46d827099008e23697583981f73108052d6/example/App.js#L52

**Comment by shababcreative** [comment]
@erezrokah Great work, thank you so much :)
