### ISSUE TITLE
Receiving PROVIDERS_CHANGED during app start causes crash on Android

### ISSUE THREAD

**Issue by JK0N** [rmrs/react-native-settings#46]
## Issue

When the app receives PROVIDERS_CHANGED during app start (before react context has been initialized) causes application to crash on Android with this error message: 

`Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
`

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android

**Comment by erezrokah** [comment]
Fixed by https://github.com/rmrs/react-native-settings/pull/47
