### ISSUE TITLE
openSettings is not a function

### ISSUE THREAD

**Issue by WrathChaos** [rmrs/react-native-settings#51]
## Issue

Simply not working on iOS, maybe you need to upgrade the iOS system.
![76399254-5eca2280-638f-11ea-80a4-01a077c2345e](https://user-images.githubusercontent.com/6813862/76400407-4ce97f00-6391-11ea-939a-ba952918f65a.png)

---

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android

</p>
</details>

**Comment by erezrokah** [comment]
Thanks @WrathChaos, will look into it. Does the example in this repo works for you?

**Comment by WrathChaos** [comment]
@erezrokah, Haven't tried yet but I checked the RN versions. I'm using the latest RN which is 0.61.5.

**Comment by WrathChaos** [comment]
@erezrokah I tried the example, unfortunately it does not work either. I tried with both `RN 0.60.4` and `RN 0.61.5`. Nothing works :(

**Comment by erezrokah** [comment]
Sorry for the late reply, I've updated the example and it works with changing the library, see [here](https://github.com/rmrs/react-native-settings/pull/53).

I've added the library via:
```
yarn add react-native-settings
cd iod
pod install
```

**Comment by WrathChaos** [comment]
Thank you so much @erezrokah , I will try it and give you the feedback. Let's close the issue, if I found another error, I will inform you :) Nice job

**Comment by Talha-Jawed** [comment]
@WrathChaos  i am facing the same issue in iOS. any luck how i resolve this issue?

```
"react-native": "0.63.4",
"react-native-settings": "^0.2.3",
```

**Comment by WrathChaos** [comment]
> @WrathChaos i am facing the same issue in iOS. any luck how i resolve this issue?
> 
> ```
> "react-native": "0.63.4",
> "react-native-settings": "^0.2.3",
> ```

Hello @Talha-Jawed 
It works after the new release. It was working 0.63.5+ but never tried the below versions.

**Comment by Talha-Jawed** [comment]
@WrathChaos still i am having a same issue in `"react-native": "0.64.0"`
<img width="329" alt="Screenshot 2021-04-05 at 12 34 37 PM" src="https://user-images.githubusercontent.com/39768820/113550133-00ac5500-960c-11eb-8d3f-17a6a3fcc649.png">
