### ISSUE TITLE
ISSUE WITH REACT NATIVE 0.60+

### ISSUE THREAD

**Issue by praveenkumart** [rmrs/react-native-settings#56]
## Issue

How to add library in react native 0.60+
pod version not working
 

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android

</p>
</details>

**Comment by erezrokah** [comment]
Hi @praveenkumart, does the example https://github.com/rmrs/react-native-settings/tree/master/example work for you? It uses react native `0.61.5`

**Comment by erezrokah** [comment]
Closing per lack of response
